# Generated by Django 4.0.3 on 2022-06-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dossier',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
