# Generated by Django 4.0.4 on 2022-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='vatpercentage',
            field=models.FloatField(),
        ),
    ]
