# Generated by Django 4.0.3 on 2022-06-20 17:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='userdefault.jpg', upload_to=users.models.upload_to, verbose_name='Image'),
        ),
    ]
