# Generated by Django 4.0.3 on 2022-05-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_expense_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
