# Generated by Django 4.0.3 on 2022-06-21 14:42

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='userdefault.jpg', upload_to=projects.models.upload_to, verbose_name='Image'),
        ),
    ]
