# Generated by Django 4.0.1 on 2022-02-09 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyect',
            name='admin',
        ),
        migrations.AddField(
            model_name='expense',
            name='id_proyect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endpoints.proyect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endpoints.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyect',
            name='id_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endpoints.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ip_proyect',
            name='id_proyect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.proyect'),
        ),
        migrations.AlterField(
            model_name='ip_proyect',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.user'),
        ),
    ]
