# Generated by Django 4.0.1 on 2022-02-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_remove_proyect_admin_expense_id_proyect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip_proyect',
            old_name='id_proyect',
            new_name='proyect',
        ),
        migrations.RenameField(
            model_name='ip_proyect',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='id_admin',
            new_name='admin',
        ),
    ]
