# Generated by Django 4.0.1 on 2022-02-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_rename_id_proyect_ip_proyect_proyect_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
    ]
