# Generated by Django 4.0.3 on 2022-06-22 11:57

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='projectdefault.jpg', upload_to=projects.models.upload_to, verbose_name='Image'),
        ),
    ]
